namespace coverlet.shared
{
    public enum ReportFormats
    {
        [FileExtension("html")]
        Html,
        [FileExtension("html")]
        Html_Light,
        [FileExtension("html")]
        Html_Dark,
        [FileExtension("html")]
        Html_BlueRed,
        [FileExtension("html")]
        HtmlSummary,
        [FileExtension("html")]
        HtmlChart,
        [FileExtension("html")]
        HtmlInline,
        [FileExtension("html")]
        HtmlInline_AzurePipelines,
        [FileExtension("html")]
        HtmlInline_AzurePipelines_Light,
        [FileExtension("html")]
        HtmlInline_AzurePipelines_Dark,
        [FileExtension("mhtml")]
        MHtml,
        [FileExtension("xml")]
        Clover,
        [FileExtension("xml")]
        Cobertura,
        [FileExtension("xml")]
        OpenCover, // PRO version only
        [FileExtension("xml")]
        SonarQube,
        [FileExtension("xml")]
        TeamCitySummary,
        [FileExtension("lcov")]
        Lcov,
        [FileExtension("xml")]
        Xml,
        [FileExtension("xml")]
        XmlSummary,
        [FileExtension("json")]
        JsonSummary,
        [FileExtension("latex")]
        Latex,
        [FileExtension("latex")]
        LatexSummary,
        [FileExtension("txt")]
        TextSummary,
        [FileExtension("txt")]
        TextDeltaSummary,
        [FileExtension("csv")]
        CsvSummary,
        [FileExtension("md")]
        MarkdownSummary,
        [FileExtension("md")]
        MarkdownSummaryGithub,
        [FileExtension("md")]
        MarkdownDeltaSummary,
        [FileExtension("svg")]
        SvgChart,
        [FileExtension("svg")]
        Badges
    }
}
